package com.just.book_appoint_system.mapper;

import com.just.book_appoint_system.domain.BookView;
import com.just.book_appoint_system.domain.BookViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_view
     *
     * @mbggenerated Sat Feb 15 11:02:50 CST 2020
     */
    int countByExample(BookViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_view
     *
     * @mbggenerated Sat Feb 15 11:02:50 CST 2020
     */
    int deleteByExample(BookViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_view
     *
     * @mbggenerated Sat Feb 15 11:02:50 CST 2020
     */
    int insert(BookView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_view
     *
     * @mbggenerated Sat Feb 15 11:02:50 CST 2020
     */
    int insertSelective(BookView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_view
     *
     * @mbggenerated Sat Feb 15 11:02:50 CST 2020
     */
    List<BookView> selectByExample(BookViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_view
     *
     * @mbggenerated Sat Feb 15 11:02:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") BookView record, @Param("example") BookViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_view
     *
     * @mbggenerated Sat Feb 15 11:02:50 CST 2020
     */
    int updateByExample(@Param("record") BookView record, @Param("example") BookViewExample example);
}