package com.just.book_appoint_system.mapper;

import com.just.book_appoint_system.domain.BorrowView;
import com.just.book_appoint_system.domain.BorrowViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BorrowViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_view
     *
     * @mbggenerated Sat Feb 15 11:01:54 CST 2020
     */
    int countByExample(BorrowViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_view
     *
     * @mbggenerated Sat Feb 15 11:01:54 CST 2020
     */
    int deleteByExample(BorrowViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_view
     *
     * @mbggenerated Sat Feb 15 11:01:54 CST 2020
     */
    int insert(BorrowView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_view
     *
     * @mbggenerated Sat Feb 15 11:01:54 CST 2020
     */
    int insertSelective(BorrowView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_view
     *
     * @mbggenerated Sat Feb 15 11:01:54 CST 2020
     */
    List<BorrowView> selectByExample(BorrowViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_view
     *
     * @mbggenerated Sat Feb 15 11:01:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") BorrowView record, @Param("example") BorrowViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_view
     *
     * @mbggenerated Sat Feb 15 11:01:54 CST 2020
     */
    int updateByExample(@Param("record") BorrowView record, @Param("example") BorrowViewExample example);
}