package com.just.book_appoint_system.mapper;

import com.just.book_appoint_system.domain.BorrowHistory;
import com.just.book_appoint_system.domain.BorrowHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BorrowHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbggenerated Fri Feb 14 22:39:30 CST 2020
     */
    int countByExample(BorrowHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbggenerated Fri Feb 14 22:39:30 CST 2020
     */
    int deleteByExample(BorrowHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbggenerated Fri Feb 14 22:39:30 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbggenerated Fri Feb 14 22:39:30 CST 2020
     */
    int insert(BorrowHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbggenerated Fri Feb 14 22:39:30 CST 2020
     */
    int insertSelective(BorrowHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbggenerated Fri Feb 14 22:39:30 CST 2020
     */
    List<BorrowHistory> selectByExample(BorrowHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbggenerated Fri Feb 14 22:39:30 CST 2020
     */
    BorrowHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbggenerated Fri Feb 14 22:39:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") BorrowHistory record, @Param("example") BorrowHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbggenerated Fri Feb 14 22:39:30 CST 2020
     */
    int updateByExample(@Param("record") BorrowHistory record, @Param("example") BorrowHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbggenerated Fri Feb 14 22:39:30 CST 2020
     */
    int updateByPrimaryKeySelective(BorrowHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbggenerated Fri Feb 14 22:39:30 CST 2020
     */
    int updateByPrimaryKey(BorrowHistory record);
}