package com.just.book_appoint_system.mapper;

import com.just.book_appoint_system.domain.Classification;
import com.just.book_appoint_system.domain.ClassificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    int countByExample(ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    int deleteByExample(ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    int insert(Classification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    int insertSelective(Classification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    List<Classification> selectByExample(ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    Classification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") Classification record, @Param("example") ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    int updateByExample(@Param("record") Classification record, @Param("example") ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    int updateByPrimaryKeySelective(Classification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    int updateByPrimaryKey(Classification record);
}