package com.just.book_appoint_system.domain;

import java.util.Date;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_name
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.isbn
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private String isbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.class_id
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.press
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private String press;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publish_time
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private String publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.description
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_imgs
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private String bookImgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.total
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.borrow_number
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private Integer borrowNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.inventory
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private Integer inventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.count
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.create_time
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.update_time
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.deleted
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.null1
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private String null1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.null2
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private String null2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.null3
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    private String null3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_name
     *
     * @return the value of book.book_name
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_name
     *
     * @param bookName the value for book.book_name
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.isbn
     *
     * @return the value of book.isbn
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.isbn
     *
     * @param isbn the value for book.isbn
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.class_id
     *
     * @return the value of book.class_id
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.class_id
     *
     * @param classId the value for book.class_id
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.press
     *
     * @return the value of book.press
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public String getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.press
     *
     * @param press the value for book.press
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setPress(String press) {
        this.press = press == null ? null : press.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publish_time
     *
     * @return the value of book.publish_time
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public String getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publish_time
     *
     * @param publishTime the value for book.publish_time
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setPublishTime(String publishTime) {
        this.publishTime = publishTime == null ? null : publishTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author
     *
     * @return the value of book.author
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author
     *
     * @param author the value for book.author
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.description
     *
     * @return the value of book.description
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.description
     *
     * @param description the value for book.description
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_imgs
     *
     * @return the value of book.book_imgs
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public String getBookImgs() {
        return bookImgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_imgs
     *
     * @param bookImgs the value for book.book_imgs
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setBookImgs(String bookImgs) {
        this.bookImgs = bookImgs == null ? null : bookImgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.total
     *
     * @return the value of book.total
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.total
     *
     * @param total the value for book.total
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.borrow_number
     *
     * @return the value of book.borrow_number
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public Integer getBorrowNumber() {
        return borrowNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.borrow_number
     *
     * @param borrowNumber the value for book.borrow_number
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setBorrowNumber(Integer borrowNumber) {
        this.borrowNumber = borrowNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.inventory
     *
     * @return the value of book.inventory
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public Integer getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.inventory
     *
     * @param inventory the value for book.inventory
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setInventory(Integer inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.count
     *
     * @return the value of book.count
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.count
     *
     * @param count the value for book.count
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.create_time
     *
     * @return the value of book.create_time
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.create_time
     *
     * @param createTime the value for book.create_time
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.update_time
     *
     * @return the value of book.update_time
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.update_time
     *
     * @param updateTime the value for book.update_time
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.deleted
     *
     * @return the value of book.deleted
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.deleted
     *
     * @param deleted the value for book.deleted
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.null1
     *
     * @return the value of book.null1
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public String getNull1() {
        return null1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.null1
     *
     * @param null1 the value for book.null1
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setNull1(String null1) {
        this.null1 = null1 == null ? null : null1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.null2
     *
     * @return the value of book.null2
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public String getNull2() {
        return null2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.null2
     *
     * @param null2 the value for book.null2
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setNull2(String null2) {
        this.null2 = null2 == null ? null : null2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.null3
     *
     * @return the value of book.null3
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public String getNull3() {
        return null3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.null3
     *
     * @param null3 the value for book.null3
     *
     * @mbggenerated Fri Feb 14 22:38:27 CST 2020
     */
    public void setNull3(String null3) {
        this.null3 = null3 == null ? null : null3.trim();
    }
}