package com.just.book_appoint_system.domain;

import java.util.Date;

public class BorrowView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_view.id
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_view.order_num
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_view.school_number
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    private String schoolNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_view.name
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_view.isbn
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    private String isbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_view.book_name
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_view.appoint_time
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    private Date appointTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_view.borrow_time
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    private Date borrowTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_view.return_time
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    private Date returnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_view.fail_time
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    private Date failTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_view.status
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    private Integer status=0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_view.deleted
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    private Integer deleted=0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_view.location
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_view.author
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_view.book_imgs
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    private String bookImgs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_view.id
     *
     * @return the value of borrow_view.id
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_view.id
     *
     * @param id the value for borrow_view.id
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_view.order_num
     *
     * @return the value of borrow_view.order_num
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_view.order_num
     *
     * @param orderNum the value for borrow_view.order_num
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_view.school_number
     *
     * @return the value of borrow_view.school_number
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public String getSchoolNumber() {
        return schoolNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_view.school_number
     *
     * @param schoolNumber the value for borrow_view.school_number
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public void setSchoolNumber(String schoolNumber) {
        this.schoolNumber = schoolNumber == null ? null : schoolNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_view.name
     *
     * @return the value of borrow_view.name
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_view.name
     *
     * @param name the value for borrow_view.name
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_view.isbn
     *
     * @return the value of borrow_view.isbn
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_view.isbn
     *
     * @param isbn the value for borrow_view.isbn
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_view.book_name
     *
     * @return the value of borrow_view.book_name
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_view.book_name
     *
     * @param bookName the value for borrow_view.book_name
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_view.appoint_time
     *
     * @return the value of borrow_view.appoint_time
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public Date getAppointTime() {
        return appointTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_view.appoint_time
     *
     * @param appointTime the value for borrow_view.appoint_time
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public void setAppointTime(Date appointTime) {
        this.appointTime = appointTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_view.borrow_time
     *
     * @return the value of borrow_view.borrow_time
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public Date getBorrowTime() {
        return borrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_view.borrow_time
     *
     * @param borrowTime the value for borrow_view.borrow_time
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public void setBorrowTime(Date borrowTime) {
        this.borrowTime = borrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_view.return_time
     *
     * @return the value of borrow_view.return_time
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public Date getReturnTime() {
        return returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_view.return_time
     *
     * @param returnTime the value for borrow_view.return_time
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public void setReturnTime(Date returnTime) {
        this.returnTime = returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_view.fail_time
     *
     * @return the value of borrow_view.fail_time
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public Date getFailTime() {
        return failTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_view.fail_time
     *
     * @param failTime the value for borrow_view.fail_time
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public void setFailTime(Date failTime) {
        this.failTime = failTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_view.status
     *
     * @return the value of borrow_view.status
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_view.status
     *
     * @param status the value for borrow_view.status
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_view.deleted
     *
     * @return the value of borrow_view.deleted
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_view.deleted
     *
     * @param deleted the value for borrow_view.deleted
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_view.location
     *
     * @return the value of borrow_view.location
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_view.location
     *
     * @param location the value for borrow_view.location
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_view.author
     *
     * @return the value of borrow_view.author
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_view.author
     *
     * @param author the value for borrow_view.author
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_view.book_imgs
     *
     * @return the value of borrow_view.book_imgs
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public String getBookImgs() {
        return bookImgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_view.book_imgs
     *
     * @param bookImgs the value for borrow_view.book_imgs
     *
     * @mbggenerated Thu Feb 20 16:48:59 CST 2020
     */
    public void setBookImgs(String bookImgs) {
        this.bookImgs = bookImgs == null ? null : bookImgs.trim();
    }
}