package com.just.book_appoint_system.domain;

import lombok.ToString;

import java.io.Serializable;
import java.util.Date;
@ToString
public class Classification implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.id
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.name
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.create_time
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.update_time
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.deleted
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    private Integer deleted=0;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.id
     *
     * @return the value of classification.id
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.id
     *
     * @param id the value for classification.id
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.name
     *
     * @return the value of classification.name
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.name
     *
     * @param name the value for classification.name
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.create_time
     *
     * @return the value of classification.create_time
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.create_time
     *
     * @param createTime the value for classification.create_time
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.update_time
     *
     * @return the value of classification.update_time
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.update_time
     *
     * @param updateTime the value for classification.update_time
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.deleted
     *
     * @return the value of classification.deleted
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.deleted
     *
     * @param deleted the value for classification.deleted
     *
     * @mbggenerated Fri Feb 14 22:37:40 CST 2020
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}